# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('direccion_empresa', models.CharField(max_length=200)),
                ('telefono_empresa', models.CharField(max_length=200)),
            ],
        ),
    ]
