# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-23 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provedor',
            new_name='Proveedor',
        ),
    ]
