# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-25 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedor', '0002_auto_20171023_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
