# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_proveedor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
