# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-01 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_auto_20171025_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='user',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellidos',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombres',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
