# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-16 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20170926_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='tipoproducto',
            name='valor_tipo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
