# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lugar',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
