# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20171031_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
