# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-23 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
